apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  type: NodePort
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 3000        # Port on the service (inside cluster)
      targetPort: 3000  # Port on the pod/container
      nodePort: 30081   # Port exposed on Minikube VM (can pick your own between 30000–32767)